services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - pdf_storage:/app/storage/pdfs
      - chroma_storage:/app/storage/chroma
    depends_on:
      mongodb:
        condition: service_started
      chromadb:
        condition: service_started
      ollama:
        condition: service_healthy
    networks:
      - backend
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
      MONGODB_DATABASE: pdf_upload_db
      OLLAMA_HOST: http://ollama:11434
      CHROMA_HOST: chromadb
      OLLAMA_EMBEDDING_MODEL: llama3

  ollama:
    image: ollama/ollama:0.1.29
    ports:
      - "11434:11434"
    volumes:
      - ./modelfile:/modelfile
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/bash", "/modelfile/start_ollama.sh"]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - backend
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: mongo:7.0.5
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - backend

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - chroma_storage:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongo_data:
  ollama_data:
  pdf_storage:
  chroma_storage:

networks:
  backend:
